### ISSUE TITLE
Investigate CustomerUsageReport

### ISSUE THREAD

**Issue by dchess** [kipp-bayarea/google_classroom#31]
https://developers.google.com/admin-sdk/reports/v1/appendix/usage/customer/classroom

Will this report give us better usage data than the userUsage endpoint we are using now?

**Comment by zkagin** [comment]
I took a look at this, and I don't think we can use it.

- It doesn't take orgUnit as a parameter, so it'll get data across all organizations.
- It doesn't appear to be any more up-to-date than the usage report.
- It looks like it provides summaries of all usage rather than on a user-by-user basis. So it has a count of classroom activity, but not the individual users.

You can play around with it here as well: https://developers.google.com/admin-sdk/reports/v1/reference/customerUsageReports/get

Closing this issue out.
