### ISSUE TITLE
Fix data conversion error on CourseWork

### ISSUE THREAD

**Issue by dchess** [kipp-bayarea/google_classroom#40]
When importing the CourseWork endpoint, the following error is occurring:
`sqlalchemy.exc.ProgrammingError: (pyodbc.ProgrammingError) ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Error converting data type nvarchar to float. (8114) (SQLExecDirectW)')`

This is either coming from the topicId or one of the dueDate/dueTime fields.

**Comment by dchess** [comment]
@zkagin The description field is being interpreted as a float by pandas initially and then string are failing to import

**Comment by dchess** [comment]
@zkagin a hacky fix that is working is to add `sorted` on the course_ids

**Comment by zkagin** [comment]
@dchess I am unable to reproduce this bug running Courses + CourseWork on an MSSQL Docker container (and removing the sorted() fix). Can you provide more info on which column / data seems to be causing the error?

I'm going to do the fix for #39 and may defer to you on whether that fixes this bug as well, if you can consistently repro.

**Comment by dchess** [comment]
@zkagin make sure you set your school year start date to 2019-07-01. Its coming from the description field of about the 3rd record in.

**Comment by zkagin** [comment]
@dchess I have that set up, but on both MSSQL and Postgres I'm not running into the error. Perhaps the order of courses is non-deterministic or dependent on which user is requesting the data.

Can you confirm that the submitted PR #44 solves this issue? It removes the sorted so it should otherwise break if it doesn't correctly fix it.

**Comment by dchess** [comment]
@zkagin This is still coming through on the latest branch. It's related to the description field in CourseWork being set as float rather than string by pandas from the first few records. We may need to explicitly set dtypes similar to how we are doing it for dates.
