### ISSUE TITLE
Merging Strategy

### ISSUE THREAD

**Issue by dchess** [kipp-bayarea/google_classroom#50]
@zkagin What strategy would you recommend for approving multiple PRs? Do you generally prefer to approve the dependent branches and merge them into the parent branch before merging all of them into master? 

Otherwise, it seems its necessary to keep rebasing after each merge.

**Comment by zkagin** [comment]
Most of the new PRs are diffed on master, so hopefully those ones can be merged directly. For the ones that are chained, I think doing a rebase is the cost of that kind of logic. Now that the broader code structure is mostly in place, I am optimistic I can separate out PRs so that they are branched off of master more often so we won't have to worry as much about it.
