### ISSUE TITLE
Support for Meet Data

### ISSUE THREAD

**Issue by denglender** [kipp-bayarea/google_classroom#65]
Classroom has an integration w/Meet, which provides video chat.  Would be great to pull in Meet usage data as well via [reports API](https://developers.google.com/admin-sdk/reports/v1/reference/activities/list) for the call_ended event.

From my perspective, the relevant columns are:

- conference_id
- device_type
- display_name
- duration_seconds
- endpoint_id
- identifier
- identifier_type
- ip_address
- is_external
- meeting_code
- organizer_email

**Comment by zkagin** [comment]
Thanks for the request @denglender! I'll take a look and see what we can do.

@dchess This data comes from a new endpoint, Activities, rather than UserUsageReport, so we will need to expand the scopes for the service accounts to include:
`https://www.googleapis.com/auth/admin.reports.audit.readonly`

Can you add this to the account permissions, and I'll add this in?

I also looked into whether the UserUsageReport or CustomerUsageReport would work for this. The former doesn't have meet data, and while the latter does, it appears to only have daily aggregated metrics (https://developers.google.com/admin-sdk/reports/v1/updated-meet-metrics) and requires separate calls per user. Unfortunately the Activities endpoint referenced above doesn't have Classroom data, so we'll need to use both.

**Comment by denglender** [comment]
I'm happy to do some testing against my domain after adding the scopes as well.
